server:
  port: 8888


spring:
  profiles:
    active: '@spring.active@'
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis:
  #classpath指存放编译文件的classes目录，classpath：只会到你的class路径中查找找文件，classpath*：不仅包含class路径，还包括jar文件中（class路径）进行查找
  mapper-locations: classpath:com/ztc/springB/*/*.xml
  #配置映射类所在的包
  typeAliasesPackage: com.ztc.springB.model

log:
  path: market-monitoring-logs

---

#配置数据源
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
     #mysql 8以上的jar使用如下驱动
     #driver-class-name: com.mysql.cj.jdbc.Driver





